# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0c3aa2c5ffc5ff9c7cd3ebf40a67843edc04aa686b7595fb88879afa641eb6c10f56c0b701915f0545d726f531788e158e707e4758498e7b765aeb22419cc6e9

test:
  secret_key_base: 4fbd75d1b2e6eb671aa72ca9abc0e87ddfb2bd177c5a994b602df78c053be78bbfa545b72edd72a05cbb384c3ff708dd44f4c4f838ca9819b9fbe95c394aac16

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
